### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by werewere** [nellore/vickitrix#7]
Hi, I'm pretty sure that I wrote all the passwords correctly (I tried three times) but it gives me this error when I start:
```
local:vickitrix setw$ python vickitrix trade
Enter password for profile "default": 
Traceback (most recent call last):
  File "vickitrix/__init__.py", line 597, in go
    get_dough(gdax_client, status_update=True)
  File "vickitrix/__init__.py", line 127, in get_dough
    dough[account['currency']] = account['available']
TypeError: string indices must be integers

Chances are, this opaque error happened because either 
a) You entered incorrect security credentials when you were configuring vickitrix.
b) You entered the wrong password above.
```
Is there any chance that it is some kind of other error?

**Comment by werewere** [comment]
Nevermind, I already solved it. It was a problem with the internet connection :/
